apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::548957227462:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RXXIXEXE6D2E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::548957227462:role/UdacityFullstack
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-24T13:24:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1596"
  uid: b2910ded-98ac-4881-b1e8-6420d613bf0b
